#ifndef KHA_CONSTANTS_H
#define	KHA_CONSTANTS_H

#ifdef	__cplusplus
extern "C" {
#endif

#define KHA_MSG_START 0x42
#define KHA_MSG_START_CONFIRM 0x99
#define KHA_MSG_START_ESCAPE 0x66
#define KHA_MSG_LEN_MIN 5 // len + from + to + cmd + crc
#define KHA_MSG_LEN_OPT_MAX 67
#define KHA_MSG_LEN_MAX (KHA_MSG_LEN_MIN + KHA_MSG_LEN_OPT_MAX)

#define KHA_ADDR_NONE 0x00
#define KHA_ADDR_UNICAST_FALLBACK 0x01
#define KHA_ADDR_BROADCAST_GROUP_NONE 0x00
#define KHA_ADDR_BROADCAST_GROUP_FALLBACK 0xF0
#define KHA_ADDR_BROADCAST_GROUP_MIN 0xF1
#define KHA_ADDR_BROADCAST_GROUP_MAX 0xFE
#define KHA_ADDR_BROADCAST 0xFF

#define KHA_BOARD_TYPE_NONE 0x00
#define KHA_BOARD_TYPE_FALLBACK 0x01
#define KHA_BOARD_TYPE_MIN 0x02
#define KHA_BOARD_TYPE_MAX 0xFE
#define KHA_BOARD_TYPE_ALL 0xFF

#define KHA_BOARD_REV_NONE 0x00
#define KHA_BOARD_REV_FALLBACK 'A'
#define KHA_BOARD_REV_MIN 'A'
#define KHA_BOARD_REV_MAX 'Z'
#define KHA_BOARD_REV_ALL 0xFF

#define KHA_PRESET_MAX 0x0F
#define KHA_PRESET_NONE 0xFF
#define KHA_PRESET_SHUTDOWN 0x01
#define KHA_PRESET_OFF 0x00

    // -------------------------------------------------------------------------

#define KHA_CMD_MANAGEMENT_REBOOT 0xFF
#define KHA_CMD_MANAGEMENT_BOOT_CMD_ERROR 0xFE
#define KHA_CMD_MANAGEMENT_BOOT_NOT_EXIT 0xFD
#define KHA_CMD_MANAGEMENT_BOOT_WIPE_FLASH 0xFC
#define KHA_CMD_MANAGEMENT_BOOT_WIPE_EEPROM 0xFB
#define KHA_CMD_MANAGEMENT_BOOT_FW_DATA 0xFA
#define KHA_CMD_MANAGEMENT_BOOT_FW_WRITE 0xF9
#define KHA_CMD_MANAGEMENT_TX_ENABLE 0xF1
#define KHA_CMD_MANAGEMENT_TX_DISABLE 0xF0

#define KHA_CMD_DEVICE_PRESET 0xED
#define KHA_CMD_DEVICE_UI_ENABLE 0xEC
#define KHA_CMD_DEVICE_UI_DISABLE 0xEB
#define KHA_CMD_DEVICE_DEBUG_ENABLE 0xEA
#define KHA_CMD_DEVICE_DEBUG_DISABLE 0xE9
#define KHA_CMD_DEVICE_DEBUG_MSG 0xE8
#define KHA_CMD_DEVICE_STATS_CLEAR 0xE7    
#define KHA_CMD_DEVICE_STATS_RESPONSE 0xE6
#define KHA_CMD_DEVICE_STATS_REQUEST 0xE5
#define KHA_CMD_DEVICE_PONG 0xE4
#define KHA_CMD_DEVICE_PING 0xE3
#define KHA_CMD_DEVICE_UP 0xE2
#define KHA_CMD_DEVICE_IDENT_RESPONSE 0xE1
#define KHA_CMD_DEVICE_IDENT_REQUEST 0xE0

#define KHA_CMD_REGISTER_CONFIG_WIPE 0xDF
#define KHA_CMD_REGISTER_CONFIG_STORE 0xDE
#define KHA_CMD_REGISTER_CONFIG_LOAD 0xDD
#define KHA_CMD_REGISTER_WRITE_FAIL 0xD8
#define KHA_CMD_REGISTER_WRITE_SUCCESS 0xD7
#define KHA_CMD_REGISTER_WRITE_REQUEST_NO_REPLY 0xD6
#define KHA_CMD_REGISTER_WRITE_REQUEST 0xD5
#define KHA_CMD_REGISTER_READ_RESPONSE 0xD1
#define KHA_CMD_REGISTER_READ_REQUEST 0xD0

#define KHA_CMD_SYSTEM_NOP 0x00

    // -------------------------------------------------------------------------

#ifdef	__cplusplus
}
#endif

#endif
